-- Copyright (c) 2024 RAMPAGE Interactive. All rights reserved.
-- Copyright (c) 2024 Metatable Games. All rights reserved.
-- Written by vq9o <business@vq9o.com>

return {
    LOBBY_TOPIC = "Matchmaking_Lobby_Update",
    PARTY_MSS_NAME = "ActivePartyData",

    PARTY_DEFAULT_MAX_SIZE = 10,
    PARTY_EXPIRATION_TIME = 3600, -- 1 hour

    BLOCK_JOINING_MID_GAME = false,
    REASSIGN_LEADER_INSTEAD_OF_DISBAND = false,

    PARTY_SERVER_SIZE_HARD_LIMIT = true,
}